const router = require("express").Router();
const { home, signupBasicInfo } = require("../controllers/signup");
const { documentUpload } = require("../controllers/documentUpload");
const { bankDetails } = require("../controllers/bankDetails");
const { saveToDB } = require("../controllers/savingToDB");
router.route("/").get(home);
router.route("/basicInfo").post(signupBasicInfo);
router.route("/documentUpload").post(documentUpload);
router.route("/bankDetails").post(bankDetails);
router.route("/otherDetails").post(saveToDB);
module.exports = router;
